import type { Permission } from "@/auth/permissions";
import type { WorkflowToolName } from "./schemas";
export const workflowPermissions = {
	get_overlay_runtime: "overlay:read",
	get_overlay_queues: "overlay:read",
	control_overlay: "overlay:control",
	enqueue_overlay_clip: "overlay:control",
	clear_overlay_queue: "overlay:control",
	search_clips: "creator:read",
	resolve_clip: "creator:read",
	preview_playlist_import: "playlist:read",
	commit_playlist_import: "playlist-items:manage",
	list_galleries: "gallery:read",
	get_gallery: "gallery:read",
	create_gallery: "gallery:create",
	update_gallery: "gallery:update",
	delete_gallery: "gallery:delete",
	publish_gallery: "gallery:publish",
	get_gallery_embed: "gallery:read",
	get_gallery_preview: "gallery:read",
	get_overlay_embed: "overlay-secret:read",
	get_player_embed: "overlay:read",
	get_creator_page: "creator:read",
	update_creator_page: "creator:update",
	publish_creator_page: "creator:update",
	get_runner_setup: "runner:read",
	list_runners: "runner:read",
	get_runner: "runner:read",
	create_runner: "runner:create",
	update_runner: "runner:update",
	delete_runner: "runner:delete",
	unlink_runner: "runner-credential:rotate",
	list_stream_sessions: "runner:read",
	get_stream_session: "runner:read",
	configure_stream_session: "runner:update",
	control_stream_session: "runner:control",
	get_runner_snapshot: "runner:read",
	submit_feedback: "creator:read",
} as const satisfies Record<WorkflowToolName, Permission>;
export const workflowDescriptions: Record<WorkflowToolName, string> = {
	get_overlay_runtime: "Read the latest connected player report, current clip and playback progress. Reports may be stale or unavailable on this server instance. Requires remote-control Pro access.",
	get_overlay_queues: "Read viewer queue for this overlay and the creator-wide moderator queue. Requires Pro.",
	control_overlay: "Send play/pause/skip/show/hide/volume/mute/unmute/toggle_mute to ONE overlay. Command acceptance is not proof of playback. Requires Pro; volume is ephemeral for this overlay.",
	enqueue_overlay_clip: "Add a validated Twitch clip from this creator to the CREATOR-WIDE moderator queue. Reuse retryKey for retries. Requires Pro.",
	clear_overlay_queue: "Clear this overlay's viewer queue and/or the CREATOR-WIDE moderator queue. This discards queued clips. Requires Pro.",
	search_clips: "Discover this creator's Twitch clips by absolute dates, category name/ID, title and view/duration filters. Pass explicit timezone for interpreting user dates; bounds are absolute. Bounded searches report incomplete results.",
	resolve_clip: "Resolve a Twitch clip ID or Twitch clip URL belonging to this creator. For a clip title, use search_clips and disambiguate candidates.",
	preview_playlist_import: "Preview exact discovered or linked clips before changing the playlist. Shows duplicate references and remaining quota; incomplete discovery cannot produce an all-clips import.",
	commit_playlist_import: "Add ONLY the exact expiring preview selection after presenting it and obtaining user confirmation. confirmed=true expresses the host's intent, not independent proof of human consent. Reuse retryKey.",
	list_galleries: "List approved creator galleries and revisions.",
	get_gallery: "Read gallery configuration and current plan capabilities.",
	create_gallery: "Create a gallery within current plan limits. Reuse retryKey.",
	update_gallery: "Edit supported gallery content/layout/styling using the latest revision; publication requires publish_gallery.",
	delete_gallery: "Delete a gallery using its current revision.",
	publish_gallery: "Publish or unpublish a gallery using its current revision and explicit publication authority.",
	get_gallery_embed: "Get the supported Clipify Elements gallery snippet and installation instructions. Raw gallery iframes are unsupported.",
	get_gallery_preview: "Read a safe paginated gallery clip preview under the creator's current plan.",
	get_overlay_embed: "Get a sensitive OBS browser-source URL only with explicit overlay-secret:read approval. This URL is private; do not embed it in a public website.",
	get_player_embed: "Get public player Elements or iframe HTML for a website without private OBS credentials.",
	get_creator_page: "Read supported Creator Page settings, revision and public URL.",
	update_creator_page: "Edit Creator Page visibility/bio/social preview settings using its revision; social fields require Pro.",
	publish_creator_page: "Enable or disable the public Creator Page using its current revision.",
	get_runner_setup: "Check separate Runner access and get official download/enrollment instructions for your platform. Human installation and enrollment approval remain required.",
	list_runners: "List approved creator runners without tokens.",
	get_runner: "Read a runner's heartbeat/connection status and revision without credentials.",
	create_runner: "Create a named runner record with Runner access; reuse retryKey. Enroll the local device through the normal user approval flow.",
	update_runner: "Rename a runner using its latest revision.",
	delete_runner: "Delete a runner and detach its sessions using its current revision.",
	unlink_runner: "Rotate a runner's credential to disconnect its enrolled device, stop its sessions, and require fresh enrollment. Requires its current revision.",
	list_stream_sessions: "List safe stream-session configuration and desired versus actual state, without stream keys or credential-bearing destinations.",
	get_stream_session: "Read a stream session and assigned runner health without credentials.",
	configure_stream_session: "Create/update runner and overlay assignments, output mode and video settings. Existing keys stay server-side; enter missing keys through the dashboard. Reuse retryKey for creation.",
	control_stream_session: "Request a stream to start or stop using its latest configuration revision. Starting broadcasts content. The runner reports actual state asynchronously.",
	get_runner_snapshot: "Get the runner's latest assigned JPEG preview with capture timestamp. Unavailable if no fresh preview exists.",
	submit_feedback: "Submit a Clipify bug report or suggestion ONLY when the user requests it and approves the message. Available on Free with existing creator read access. Do not submit automatically on tool failures or include transcripts, credentials or screenshots. Five distinct reports per user per 24 hours on this server process. Reuse retryKey; RAM limits and deduplication reset on restart. A queued receipt is not proof of delivery.",
};
export function workflowAnnotations(name: WorkflowToolName) {
	if (name === "submit_feedback") return { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true };
	const read = name.startsWith("get_") || name.startsWith("list_") || ["search_clips", "resolve_clip", "preview_playlist_import"].includes(name);
	return { readOnlyHint: read, destructiveHint: !read && !name.startsWith("create_"), idempotentHint: !["control_overlay", "enqueue_overlay_clip", "clear_overlay_queue", "control_stream_session", "unlink_runner"].includes(name), openWorldHint: ["search_clips", "resolve_clip", "preview_playlist_import", "commit_playlist_import", "enqueue_overlay_clip"].includes(name) };
}
