# -------------------------
# deps
# -------------------------
FROM oven/bun:1 AS deps
WORKDIR /app

# build deps for node-gyp (re2, etc.) - only in deps stage
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock ./
COPY patches ./patches

RUN --mount=type=cache,target=/root/.bun \
    bun install --frozen-lockfile

# -------------------------
# builder
# -------------------------
FROM oven/bun:1 AS builder
WORKDIR /app
ARG COOLIFY_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN bun run app:build


# -------------------------
# runner (preview)
# -------------------------
FROM oven/bun:1 AS runner
WORKDIR /app

ENV NODE_ENV=development
ENV IS_PREVIEW=true
ENV INFISICAL_API_URL=https://infisical.thedannicraft.de
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

ARG TARGETARCH
ARG INFISICAL_VERSION=0.43.46
ARG INFISICAL_SHA_AMD64=3457a1f9fa51f1b04bb759bd60fd5ee77dc51509ac4058248cb8c68b1b1372ff
ARG INFISICAL_SHA_ARM64=89bd57b8ed9934c421565397bb8fdaf4906b61bae2b6d8b68eca2af01393b605

# minimal deps + create user
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    adduser && \
    rm -rf /var/lib/apt/lists/* && \
    addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# install infisical CLI
RUN set -eux; \
    case "${TARGETARCH}" in \
    amd64) \
    INF_ARCH="amd64"; \
    INF_SHA="${INFISICAL_SHA_AMD64}"; \
    ;; \
    arm64) \
    INF_ARCH="arm64"; \
    INF_SHA="${INFISICAL_SHA_ARM64}"; \
    ;; \
    *) echo "Unsupported arch: ${TARGETARCH}" && exit 1 ;; \
    esac; \
    \
    file="cli_${INFISICAL_VERSION}_linux_${INF_ARCH}.tar.gz"; \
    url="https://github.com/Infisical/cli/releases/download/v${INFISICAL_VERSION}/${file}"; \
    tmp="/tmp/${file}"; \
    \
    curl -fsSL "$url" -o "$tmp"; \
    \
    echo "${INF_SHA}  ${tmp}" | sha256sum -c -; \
    \
    tar -xzf "$tmp" -C /usr/local/bin; \
    rm -f "$tmp"; \
    chmod +x /usr/local/bin/infisical; \
    infisical --version

# app files
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/drizzle.config.ts ./
COPY --from=builder --chown=nextjs:nodejs /app/src/db/schema.ts ./src/db/schema.ts

USER nextjs
EXPOSE 3000

CMD ["infisical", "run", "--projectId", "4bea168c-8d4c-4086-b755-f04fdc5305a1", "--command", "bun run db:push && bun server.js || sleep infinity"]
