@BDD @ATDD @US3 @FR-008 @EC-007 @BDD-READ-AUTHORITY-001
Feature: Read access follows current backend authority
  Scenario Outline: Current role access path and selected creator govern every read
    Given the current read access case is "<phase>" for "<tool>"
    When the validly authenticated client attempts that read through the MCP route
    Then the read reports "<code>" with creator filtering "<filtered>" and no secrets or resource changes
    Examples:
      | phase | tool | code | filtered |
      | owner-pro | list_creators | NONE | false |
      | owner-pro | get_capabilities | NONE | false |
      | owner-pro | list_overlays | NONE | false |
      | owner-pro | get_overlay | NONE | false |
      | owner-pro | list_playlists | NONE | false |
      | owner-pro | get_playlist | NONE | false |
      | owner-free | list_creators | NONE | false |
      | owner-free | get_capabilities | NONE | false |
      | owner-free | list_overlays | NONE | false |
      | owner-free | get_overlay | NONE | false |
      | owner-free | list_playlists | NONE | false |
      | owner-free | get_playlist | NONE | false |
      | direct-pro | list_creators | NONE | false |
      | direct-pro | get_capabilities | NONE | false |
      | direct-pro | list_overlays | NONE | false |
      | direct-pro | get_overlay | NONE | false |
      | direct-pro | list_playlists | NONE | false |
      | direct-pro | get_playlist | NONE | false |
      | direct-free | list_creators | NONE | true |
      | direct-free | get_capabilities | ACCESS_DENIED | false |
      | direct-free | list_overlays | ACCESS_DENIED | false |
      | direct-free | get_overlay | ACCESS_DENIED | false |
      | direct-free | list_playlists | ACCESS_DENIED | false |
      | direct-free | get_playlist | ACCESS_DENIED | false |
      | denied-role | list_creators | NONE | true |
      | denied-role | get_capabilities | ACCESS_DENIED | false |
      | denied-role | list_overlays | ACCESS_DENIED | false |
      | denied-role | get_overlay | ACCESS_DENIED | false |
      | denied-role | list_playlists | ACCESS_DENIED | false |
      | denied-role | get_playlist | ACCESS_DENIED | false |
      | custom-direct | list_creators | NONE | false |
      | custom-direct | get_capabilities | NONE | false |
      | custom-direct | list_overlays | NONE | false |
      | custom-direct | get_overlay | NONE | false |
      | custom-direct | list_playlists | ACCESS_DENIED | false |
      | custom-direct | get_playlist | ACCESS_DENIED | false |
      | agency-pro | list_creators | NONE | false |
      | agency-pro | get_capabilities | NONE | false |
      | agency-pro | list_overlays | NONE | false |
      | agency-pro | get_overlay | NONE | false |
      | agency-pro | list_playlists | NONE | false |
      | agency-pro | get_playlist | NONE | false |
      | agency-free | list_creators | NONE | false |
      | agency-free | get_capabilities | NONE | false |
      | agency-free | list_overlays | NONE | false |
      | agency-free | get_overlay | NONE | false |
      | agency-free | list_playlists | NONE | false |
      | agency-free | get_playlist | NONE | false |
      | agency-ceiling | list_creators | NONE | false |
      | agency-ceiling | get_capabilities | NONE | false |
      | agency-ceiling | list_overlays | NONE | false |
      | agency-ceiling | get_overlay | NONE | false |
      | agency-ceiling | list_playlists | ACCESS_DENIED | false |
      | agency-ceiling | get_playlist | ACCESS_DENIED | false |
      | agency-inactive | list_creators | NONE | true |
      | agency-inactive | get_capabilities | ACCESS_DENIED | false |
      | agency-inactive | list_overlays | ACCESS_DENIED | false |
      | agency-inactive | get_overlay | ACCESS_DENIED | false |
      | agency-inactive | list_playlists | ACCESS_DENIED | false |
      | agency-inactive | get_playlist | ACCESS_DENIED | false |
      | agency-custom-role | list_creators | NONE | false |
      | agency-custom-role | get_capabilities | NONE | false |
      | agency-custom-role | list_overlays | ACCESS_DENIED | false |
      | agency-custom-role | get_overlay | ACCESS_DENIED | false |
      | agency-custom-role | list_playlists | NONE | false |
      | agency-custom-role | get_playlist | NONE | false |
      | creator-suspended | list_creators | NONE | true |
      | creator-suspended | get_capabilities | ACCESS_DENIED | false |
      | creator-suspended | list_overlays | ACCESS_DENIED | false |
      | creator-suspended | get_overlay | ACCESS_DENIED | false |
      | creator-suspended | list_playlists | ACCESS_DENIED | false |
      | creator-suspended | get_playlist | ACCESS_DENIED | false |
      | creator-disabled | list_creators | NONE | true |
      | creator-disabled | get_capabilities | ACCESS_DENIED | false |
      | creator-disabled | list_overlays | ACCESS_DENIED | false |
      | creator-disabled | get_overlay | ACCESS_DENIED | false |
      | creator-disabled | list_playlists | ACCESS_DENIED | false |
      | creator-disabled | get_playlist | ACCESS_DENIED | false |
      | unapproved-creator | get_capabilities | ACCESS_DENIED | false |
      | unapproved-creator | list_overlays | ACCESS_DENIED | false |
      | unapproved-creator | get_overlay | ACCESS_DENIED | false |
      | unapproved-creator | list_playlists | ACCESS_DENIED | false |
      | unapproved-creator | get_playlist | ACCESS_DENIED | false |
      | missing-context | get_capabilities | INVALID_INPUT | false |
      | missing-context | list_overlays | INVALID_INPUT | false |
      | missing-context | get_overlay | INVALID_INPUT | false |
      | missing-context | list_playlists | INVALID_INPUT | false |
      | missing-context | get_playlist | INVALID_INPUT | false |
      | malformed-context | get_capabilities | INVALID_INPUT | false |
      | malformed-context | list_overlays | INVALID_INPUT | false |
      | malformed-context | get_overlay | INVALID_INPUT | false |
      | malformed-context | list_playlists | INVALID_INPUT | false |
      | malformed-context | get_playlist | INVALID_INPUT | false |
      | foreign-resource | get_overlay | RESOURCE_UNAVAILABLE | false |
      | foreign-resource | get_playlist | RESOURCE_UNAVAILABLE | false |
      | empty-selection | list_creators | NONE | true |
      | empty-selection | get_capabilities | ACCESS_DENIED | false |
      | empty-selection | list_overlays | ACCESS_DENIED | false |
      | empty-selection | get_overlay | ACCESS_DENIED | false |
      | empty-selection | list_playlists | ACCESS_DENIED | false |
      | empty-selection | get_playlist | ACCESS_DENIED | false |
      | agency-ceiling-write | create_overlay | ACCESS_DENIED | false |
      | agency-ceiling-write | update_overlay | ACCESS_DENIED | false |
      | agency-ceiling-write | delete_overlay | ACCESS_DENIED | false |
      | agency-ceiling-write | create_playlist | ACCESS_DENIED | false |
      | agency-ceiling-write | update_playlist | ACCESS_DENIED | false |
      | agency-ceiling-write | delete_playlist | ACCESS_DENIED | false |
      | agency-ceiling-write | add_playlist_items | ACCESS_DENIED | false |
      | agency-ceiling-write | remove_playlist_items | ACCESS_DENIED | false |
      | agency-ceiling-write | reorder_playlist_items | ACCESS_DENIED | false |
