export const CROSSFADE_SECONDS = 0.7;
export const CROSSFADE_MS = Math.round(CROSSFADE_SECONDS * 1000);
export const SHOW_FADE_SECONDS = 0.6;
export const HOLD_FRAME_SECONDS = 0.08;
export const HOLD_TIMEOUT_MS = 1500;

export const NEXT_VIDEO_PREPARE_SECONDS = 8;
export const ACTIVE_PLAYBACK_CONFIRM_SECONDS = 0.5;

export const PLAYBACK_WATCHDOG_INTERVAL_MS = 1000;
export const PLAYBACK_STALL_THRESHOLD_MS = 5000;
export const PLAYBACK_PROGRESS_EPSILON_SECONDS = 0.05;
export const PLAYBACK_RECOVERY_RECHECK_MS = 1250;
export const PLAYBACK_LOAD_TIMEOUT_MS = 3000;
export const PLAYBACK_BUFFERING_GRACE_MS = 2000;
export const PLAYBACK_ISSUE_REPORT_COOLDOWN_MS = 30_000;
