import type { Permission } from "@/auth/permissions";
import type { ToolName } from "./schemas";

type ToolMetadata = {
	title: string;
	description: string;
	permission: Permission;
	public: boolean;
	annotations: { readOnlyHint: boolean; destructiveHint: boolean; idempotentHint: boolean; openWorldHint: boolean };
};

/** Data only: safe for activity labels; schemas and handlers stay in server modules.
 * Every write uses a conservative confirmation hint. Hints never grant authority.
 * Idempotent creates still require the same retained retry key.
 */
export const mcpToolCatalogue = {
	get_overlay_source: {
		title: "Read overlay source",
		description: "Read overlay clip source type and linked playlist; use list_playlists to find a playlist. Returns the saved settings and current configurationRevision; excludes unrelated fields and private links.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_overlay_source: {
		title: "Edit overlay source",
		description: "Change only overlay clip source type and linked playlist; use list_playlists to find a playlist. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Existing creator permissions and plan restrictions apply.",
		permission: "overlay:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_filters: {
		title: "Read overlay filters",
		description: "Read overlay clip duration in seconds, minimum views, Twitch category-ID and clip-creator username allow/block lists, and blocked title words; arrays replace the specified list. Returns the saved settings and current configurationRevision; excludes unrelated fields and private links.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_overlay_filters: {
		title: "Edit overlay filters",
		description: "Change only overlay clip duration in seconds, minimum views, Twitch category-ID and clip-creator username allow/block lists, and blocked title words; arrays replace the specified list. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Existing creator permissions and plan restrictions apply.",
		permission: "overlay:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_playback: {
		title: "Read overlay playback",
		description: "Read overlay playback mode, current-category preference, clip pack size and saved volume; use control_overlay for temporary live volume changes. Returns the saved settings and current configurationRevision; excludes unrelated fields and private links.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_overlay_playback: {
		title: "Edit overlay playback",
		description: "Change only overlay playback mode, current-category preference, clip pack size and saved volume; use control_overlay for temporary live volume changes. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Existing creator permissions and plan restrictions apply.",
		permission: "overlay:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_theme: {
		title: "Read overlay theme",
		description: "Read overlay Theme Studio appearance: fonts, colors, borders in pixels, effects, visible information, positions (0–100 percent) and scales (50–250 percent). Returns the saved settings and current configurationRevision; excludes unrelated fields and private links.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_overlay_theme: {
		title: "Edit overlay theme",
		description: "Change only overlay Theme Studio appearance: fonts, colors, borders in pixels, effects, visible information, positions (0–100 percent) and scales (50–250 percent). Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Existing creator permissions and plan restrictions apply.",
		permission: "overlay:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	update_overlay_settings: {
		title: "Edit overlay settings",
		description: "Change only overlay name and enabled/paused status. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Existing creator permissions and plan restrictions apply.",
		permission: "overlay:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_gallery_source: {
		title: "Read gallery source",
		description: "Read curated playlist or live Twitch clips; use list_playlists to find a playlist. Returns saved settings, configurationRevision and current capabilities.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_gallery_source: {
		title: "Edit gallery source",
		description: "Change only curated playlist or live Twitch clips; use list_playlists to find a playlist. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Does not publish; use publish_gallery. Existing creator permissions and plan restrictions apply.",
		permission: "gallery:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_gallery_filters: {
		title: "Read gallery filters",
		description: "Read live clip sorting, date window, result limit, views/duration and Twitch category-ID/creator-username/title filters; arrays replace the specified list. Returns saved settings, configurationRevision and current capabilities.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_gallery_filters: {
		title: "Edit gallery filters",
		description: "Change only live clip sorting, date window, result limit, views/duration and Twitch category-ID/creator-username/title filters; arrays replace the specified list. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Does not publish; use publish_gallery. Existing creator permissions and plan restrictions apply.",
		permission: "gallery:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_gallery_layout: {
		title: "Read gallery layout",
		description: "Read grid/list/carousel layout, responsive columns/cards, navigation and visible clip metadata. Returns saved settings, configurationRevision and current capabilities.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_gallery_layout: {
		title: "Edit gallery layout",
		description: "Change only grid/list/carousel layout, responsive columns/cards, navigation and visible clip metadata. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Does not publish; use publish_gallery. Existing creator permissions and plan restrictions apply.",
		permission: "gallery:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_gallery_theme: {
		title: "Read gallery theme",
		description: "Read colors, surfaces, corners, spacing, thumbnails and clip modal appearance. Returns saved settings, configurationRevision and current capabilities.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_gallery_theme: {
		title: "Edit gallery theme",
		description: "Change only colors, surfaces, corners, spacing, thumbnails and clip modal appearance. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Does not publish; use publish_gallery. Existing creator permissions and plan restrictions apply.",
		permission: "gallery:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	update_gallery_settings: {
		title: "Edit gallery settings",
		description: "Change only gallery name. Send a nonempty partial patch and expectedRevision from the latest read. Omitted fields stay unchanged. Returns updated settings and revision. Does not publish; use publish_gallery. Existing creator permissions and plan restrictions apply.",
		permission: "gallery:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_link: {
		title: "Read private streaming source URL",
		description: "Get the private browser-source URL for OBS Studio, Streamlabs or another streaming application. Requires explicit overlay-secret:read permission. The URL contains a credential: do not publish it or include it in public website HTML. Use get_player_embed for public websites.",
		permission: "overlay-secret:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	list_creators: {
		title: "List creators",
		description: "List approved creators you can currently access",
		permission: "creator:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_capabilities: {
		title: "Check capabilities",
		description: "Read a creator's current plan limits, usage and permitted operations",
		permission: "creator:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	list_overlays: {
		title: "List overlays",
		description: "Read approved creator overlays without private credentials",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_overlay: {
		title: "Read overlay",
		description: "Read one approved creator overlay without private credentials",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	create_overlay: {
		title: "Create overlay",
		description: "Create an overlay within the creator's plan limits. Reuse the same retry key for retries of this request.",
		permission: "overlay:create",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	update_overlay: {
		title: "Update overlay",
		description: "Edit supported overlay configuration using its current revision. Internal browser/backend compatibility operation; not exposed as an MCP tool.",
		permission: "overlay:update",
		public: false,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	delete_overlay: {
		title: "Delete overlay",
		description: "Delete an overlay with explicit delete permission and its current revision",
		permission: "overlay:delete",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	list_playlists: {
		title: "List playlists",
		description: "List approved creator playlists and their configuration revisions",
		permission: "playlist:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_playlist: {
		title: "Read playlist",
		description: "Read approved playlist metadata and ordered safe clip references",
		permission: "playlist:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	create_playlist: {
		title: "Create playlist",
		description: "Create a playlist within the creator's plan limits. Reuse the same retry key when retrying.",
		permission: "playlist:create",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	update_playlist: {
		title: "Rename playlist",
		description: "Rename a playlist using its current configuration revision",
		permission: "playlist:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	delete_playlist: {
		title: "Delete playlist",
		description: "Delete a playlist with explicit delete permission and its current revision; clear linked overlay and gallery references",
		permission: "playlist:delete",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	add_playlist_items: {
		title: "Add playlist clips",
		description: "Append Twitch-validated clips within the creator's current plan limits using the playlist revision",
		permission: "playlist-items:manage",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
	},
	remove_playlist_items: {
		title: "Remove playlist clips",
		description: "Remove selected existing playlist items and return their remaining order using the current revision",
		permission: "playlist-items:manage",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	reorder_playlist_items: {
		title: "Reorder playlist clips",
		description: "Replace playlist item order with an exact permutation using its current revision",
		permission: "playlist-items:manage",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_runtime: {
		title: "Read live overlay state",
		description: "Read the latest connected player report, current clip and playback progress. Reports may be stale or unavailable on this server instance. Requires remote-control Pro access.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_queues: {
		title: "Read overlay queues",
		description: "Read viewer queue for this overlay and the creator-wide moderator queue. Requires Pro.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	control_overlay: {
		title: "Control live overlay",
		description: "Send play/pause/skip/show/hide/volume/mute/unmute/toggle_mute to ONE overlay. Command acceptance is not proof of playback. Requires Pro; volume is ephemeral for this overlay.",
		permission: "overlay:control",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
	},
	enqueue_overlay_clip: {
		title: "Queue a creator clip",
		description: "Add a validated Twitch clip from this creator to the CREATOR-WIDE moderator queue. Reuse retryKey for retries. Requires Pro.",
		permission: "overlay:control",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
	},
	clear_overlay_queue: {
		title: "Clear overlay queue",
		description: "Clear this overlay's viewer queue and/or the CREATOR-WIDE moderator queue. This discards queued clips. Requires Pro.",
		permission: "overlay:control",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
	},
	search_clips: {
		title: "Find creator clips",
		description: "Discover this creator's Twitch clips by absolute dates, category name/ID, title and view/duration filters. Pass explicit timezone for interpreting user dates; bounds are absolute. Bounded searches report incomplete results.",
		permission: "creator:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
	},
	resolve_clip: {
		title: "Resolve a Twitch clip",
		description: "Resolve a Twitch clip ID or Twitch clip URL belonging to this creator. For a clip title, use search_clips and disambiguate candidates.",
		permission: "creator:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
	},
	preview_playlist_import: {
		title: "Preview clip import",
		description: "Preview exact discovered or linked clips before changing the playlist. Shows duplicate references and remaining quota; incomplete discovery cannot produce an all-clips import.",
		permission: "playlist:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
	},
	commit_playlist_import: {
		title: "Import previewed clips",
		description: "Add ONLY the exact expiring preview selection after presenting it and obtaining user confirmation. confirmed=true expresses the host's intent, not independent proof of human consent. Reuse retryKey.",
		permission: "playlist-items:manage",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
	},
	list_galleries: {
		title: "List galleries",
		description: "List approved creator galleries and revisions.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_gallery: {
		title: "Read gallery",
		description: "Read gallery configuration and current plan capabilities.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	create_gallery: {
		title: "Create gallery",
		description: "Create a gallery within current plan limits. Reuse retryKey.",
		permission: "gallery:create",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	update_gallery: {
		title: "Edit gallery",
		description: "Edit supported gallery content/layout/styling using the latest revision; publication requires publish_gallery.",
		permission: "gallery:update",
		public: false,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	delete_gallery: {
		title: "Delete gallery",
		description: "Delete a gallery using its current revision.",
		permission: "gallery:delete",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	publish_gallery: {
		title: "Change gallery publication",
		description: "Publish or unpublish a gallery using its current revision and explicit publication authority.",
		permission: "gallery:publish",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
	},
	get_gallery_embed: {
		title: "Get gallery embed",
		description: "Get the supported Clipify Elements gallery snippet and installation instructions. Raw gallery iframes are unsupported.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_gallery_preview: {
		title: "Preview gallery clips",
		description: "Read a safe paginated gallery clip preview under the creator's current plan.",
		permission: "gallery:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_overlay_embed: {
		title: "Read private OBS source URL",
		description: "Get a sensitive OBS browser-source URL only with explicit overlay-secret:read approval. This URL is private; do not embed it in a public website.",
		permission: "overlay-secret:read",
		public: false,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_player_embed: {
		title: "Get public player embed",
		description: "Get public player Elements or iframe HTML for a website without private OBS credentials.",
		permission: "overlay:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_creator_page: {
		title: "Read Creator Page",
		description: "Read supported Creator Page settings, revision and public URL.",
		permission: "creator:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	update_creator_page: {
		title: "Edit Creator Page",
		description: "Edit Creator Page visibility/bio/social preview settings using its revision; social fields require Pro.",
		permission: "creator:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	publish_creator_page: {
		title: "Change Creator Page publication",
		description: "Enable or disable the public Creator Page using its current revision.",
		permission: "creator:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
	},
	get_runner_setup: {
		title: "Get runner setup instructions",
		description: "Check separate Runner access and get official download/enrollment instructions for your platform. Human installation and enrollment approval remain required.",
		permission: "runner:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	list_runners: {
		title: "List runners",
		description: "List approved creator runners without tokens.",
		permission: "runner:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_runner: {
		title: "Read runner status",
		description: "Read a runner's heartbeat/connection status and revision without credentials.",
		permission: "runner:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	create_runner: {
		title: "Create runner",
		description: "Create a named runner record with Runner access; reuse retryKey. Enroll the local device through the normal user approval flow.",
		permission: "runner:create",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	update_runner: {
		title: "Rename runner",
		description: "Rename a runner using its latest revision.",
		permission: "runner:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	delete_runner: {
		title: "Delete runner",
		description: "Delete a runner and detach its sessions using its current revision.",
		permission: "runner:delete",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	unlink_runner: {
		title: "Disconnect runner device",
		description: "Rotate a runner's credential to disconnect its enrolled device, stop its sessions, and require fresh enrollment. Requires its current revision.",
		permission: "runner-credential:rotate",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
	},
	list_stream_sessions: {
		title: "List stream sessions",
		description: "List safe stream-session configuration and desired versus actual state, without stream keys or credential-bearing destinations.",
		permission: "runner:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	get_stream_session: {
		title: "Read stream session",
		description: "Read a stream session and assigned runner health without credentials.",
		permission: "runner:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	configure_stream_session: {
		title: "Configure stream session",
		description: "Create/update runner and overlay assignments, output mode and video settings. Existing keys stay server-side; enter missing keys through the dashboard. Reuse retryKey for creation.",
		permission: "runner:update",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
	},
	control_stream_session: {
		title: "Request stream start or stop",
		description: "Request a stream to start or stop using its latest configuration revision. Starting broadcasts content. The runner reports actual state asynchronously.",
		permission: "runner:control",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
	},
	get_runner_snapshot: {
		title: "Read runner snapshot",
		description: "Get the runner's latest assigned JPEG preview with capture timestamp. Unavailable if no fresh preview exists.",
		permission: "runner:read",
		public: true,
		annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
	},
	submit_feedback: {
		title: "Submit feedback",
		description: "Submit a Clipify bug report or suggestion ONLY when the user requests it and approves the message. Available on Free with existing creator read access. Do not submit automatically on tool failures or include transcripts, credentials or screenshots. Five distinct reports per user per 24 hours on this server process. Reuse retryKey; RAM limits and deduplication reset on restart. A queued receipt is not proof of delivery.",
		permission: "creator:read",
		public: true,
		annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
	},
} satisfies Record<ToolName, ToolMetadata>;
