import type { Gallery, TwitchClip } from "@types";

export const buildGallery = (patch: Partial<Gallery> = {}): Gallery => ({
	id: "gallery-1",
	ownerId: "owner",
	name: "Highlights",
	published: true,
	source: "live",
	playlistId: null,
	layout: "grid",
	gridAuto: true,
	gridMobileColumns: 1,
	gridTabletColumns: 3,
	gridDesktopColumns: 4,
	listDensity: "comfortable",
	carouselMobileCards: 1,
	carouselTabletCards: 2,
	carouselDesktopCards: 3,
	carouselShowNavigation: true,
	carouselShowIndicators: true,
	showTitle: true,
	showCreator: true,
	showViews: true,
	showDuration: true,
	showCreatedAt: false,
	liveSort: "newest",
	liveTimeWindow: "all",
	liveCustomStart: null,
	liveCustomEnd: null,
	liveResultLimit: 12,
	includeCategories: [],
	excludeCategories: [],
	minimumViews: 0,
	minimumDuration: 0,
	maximumDuration: 0,
	titleBlacklist: [],
	creatorAllowlist: [],
	creatorBlocklist: [],
	theme: "system",
	accentColor: "#7C3AED",
	backgroundMode: "transparent",
	backgroundColor: "#000000",
	cardSurfaceColor: "#18181B",
	textColor: "#FFFFFF",
	cardRadius: 16,
	gap: 16,
	thumbnailTreatment: "cover",
	modalBackdrop: "rgba(0,0,0,0.72)",
	desktopModalWidth: 960,
	createdAt: new Date("2026-01-01T00:00:00Z"),
	updatedAt: new Date("2026-01-01T00:00:00Z"),
	...patch,
});

export const buildClip = (id: string, patch: Partial<TwitchClip> = {}): TwitchClip => ({
	id,
	url: `https://clips.twitch.tv/${id}`,
	embed_url: "",
	broadcaster_id: "owner",
	broadcaster_name: "Owner",
	creator_id: `creator-${id}`,
	creator_name: `Creator ${id}`,
	video_id: "",
	game_id: "game",
	language: "en",
	title: `Clip ${id}`,
	view_count: 1_234,
	created_at: "2026-08-01T12:00:00Z",
	thumbnail_url: `${id}.jpg`,
	duration: 65,
	...patch,
});
