export const mcpOperationLabels: Record<string, string> = {
	get_overlay_source: "Read overlay source",
	update_overlay_source: "Edit overlay source",
	get_overlay_filters: "Read overlay filters",
	update_overlay_filters: "Edit overlay filters",
	get_overlay_playback: "Read overlay playback",
	update_overlay_playback: "Edit overlay playback",
	get_overlay_theme: "Read overlay theme",
	update_overlay_theme: "Edit overlay theme",
	update_overlay_settings: "Edit overlay settings",
	get_gallery_source: "Read gallery source",
	update_gallery_source: "Edit gallery source",
	get_gallery_filters: "Read gallery filters",
	update_gallery_filters: "Edit gallery filters",
	get_gallery_layout: "Read gallery layout",
	update_gallery_layout: "Edit gallery layout",
	get_gallery_theme: "Read gallery theme",
	update_gallery_theme: "Edit gallery theme",
	update_gallery_settings: "Edit gallery settings",
	get_overlay_link: "Read private streaming source URL",
	list_creators: "List creators",
	get_capabilities: "Check capabilities",
	list_overlays: "List overlays",
	get_overlay: "Read overlay",
	create_overlay: "Create overlay",
	update_overlay: "Update overlay",
	delete_overlay: "Delete overlay",
	list_playlists: "List playlists",
	get_playlist: "Read playlist",
	create_playlist: "Create playlist",
	update_playlist: "Rename playlist",
	delete_playlist: "Delete playlist",
	add_playlist_items: "Add playlist clips",
	remove_playlist_items: "Remove playlist clips",
	reorder_playlist_items: "Reorder playlist clips",
	get_overlay_runtime: "Read live overlay state",
	get_overlay_queues: "Read overlay queues",
	control_overlay: "Control live overlay",
	enqueue_overlay_clip: "Queue a creator clip",
	clear_overlay_queue: "Clear overlay queue",
	search_clips: "Find creator clips",
	resolve_clip: "Resolve a Twitch clip",
	preview_playlist_import: "Preview clip import",
	commit_playlist_import: "Import previewed clips",
	list_galleries: "List galleries",
	get_gallery: "Read gallery",
	create_gallery: "Create gallery",
	update_gallery: "Edit gallery",
	delete_gallery: "Delete gallery",
	publish_gallery: "Change gallery publication",
	get_gallery_embed: "Get gallery embed",
	get_gallery_preview: "Preview gallery clips",
	get_overlay_embed: "Read private OBS source URL",
	get_player_embed: "Get public player embed",
	get_creator_page: "Read Creator Page",
	update_creator_page: "Edit Creator Page",
	publish_creator_page: "Change Creator Page publication",
	get_runner_setup: "Get runner setup instructions",
	list_runners: "List runners",
	get_runner: "Read runner status",
	create_runner: "Create runner",
	update_runner: "Rename runner",
	delete_runner: "Delete runner",
	unlink_runner: "Disconnect runner device",
	list_stream_sessions: "List stream sessions",
	get_stream_session: "Read stream session",
	configure_stream_session: "Configure stream session",
	control_stream_session: "Request stream start or stop",
	get_runner_snapshot: "Read runner snapshot",
	submit_feedback: "Submit feedback",
};
